# Generated by Django 5.2.3 on 2025-07-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0045_userprofile_hide_bundles_bookmarkbundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkbundle",
            name="show_count",
            field=models.BooleanField(default=True, verbose_name="显示标签数"),
        ),
    ]
