# Generated by Django 5.2.3 on 2025-07-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0046_bookmarkbundle_show_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="preview_image_remote_url",
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name="bookmarkbundle",
            name="is_folder",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="landing_page",
            field=models.CharField(
                choices=[("login", "登录页"), ("shared_bookmarks", "分享页")],
                default="login",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bookmark_date_display",
            field=models.CharField(
                choices=[
                    ("relative", "相对"),
                    ("absolute", "绝对"),
                    ("hidden", "隐藏"),
                ],
                default="relative",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bookmark_description_display",
            field=models.CharField(
                choices=[("inline", "行内"), ("separate", "分行")],
                default="inline",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bookmark_link_target",
            field=models.CharField(
                choices=[("_blank", "新页面"), ("_self", "当前页面")],
                default="_blank",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tag_grouping",
            field=models.CharField(
                choices=[("alphabetical", "首字母"), ("disabled", "禁用")],
                default="alphabetical",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tag_search",
            field=models.CharField(
                choices=[("strict", "严格 Strict"), ("lax", "宽松 Lax")],
                default="strict",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("auto", "自动"), ("light", "亮色"), ("dark", "暗色")],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="web_archive_integration",
            field=models.CharField(
                choices=[("disabled", "禁用"), ("enabled", "启用")],
                default="disabled",
                max_length=10,
            ),
        ),
    ]
