# Generated by Django 5.2.3 on 2025-07-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0047_bookmark_preview_image_remote_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
