# Generated by Django 5.2.3 on 2025-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0048_bookmark_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="date_deleted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
