# Generated by Django 5.2.5 on 2025-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0061_alter_userprofile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="legacy_search",
            field=models.BooleanField(default=False),
        ),
    ]
