# Generated by Django 5.2.3 on 2025-07-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0049_add_date_deleted_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="trash_search_preferences",
            field=models.JSONField(default=dict),
        ),
    ]
