# Generated by Django 5.2.3 on 2025-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0050_add_trash_search_preferences_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="custom_domain_root",
            field=models.TextField(blank=True, default=""),
        ),
    ]
