# Generated by Django 5.2.3 on 2025-08-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0051_userprofile_custom_domain_root"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkbundle",
            name="search_params",
            field=models.JSONField(blank=True, default=dict, verbose_name="搜索参数"),
        ),
    ]
