# Generated by Django 5.2.3 on 2025-08-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0052_bookmarkbundle_search_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sticky_header_controls",
            field=models.BooleanField(default=False),
        ),
    ]
