# Generated by Django 5.2.3 on 2025-08-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0053_userprofile_sticky_header_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="sticky_side_panel",
            field=models.BooleanField(default=False),
        ),
    ]
