# Generated by Django 5.2.3 on 2025-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0054_userprofile_sticky_side_panel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmarkbundle",
            name="show_count",
            field=models.BooleanField(default=True, verbose_name="显示书签数"),
        ),
    ]
