# Generated by Django 5.2.3 on 2025-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0055_bookmarkbundle_show_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="url_normalized",
            field=models.CharField(blank=True, db_index=True, max_length=2048),
        ),
    ]
