# Generated by Django 5.2.4 on 2026-04-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0058_userprofile_default_mark_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                default="en",
                max_length=20,
            ),
        ),
    ]
