# Generated by Django 5.2.5 on 2025-10-05 10:01
# 来自上游，使用 Toast 提醒用户搜索引擎变更，可以从设置中切换回老引擎（兼容模式）
# 本项目不需要，因此移除

from django.db import migrations


def forwards(apps, schema_editor):
    pass


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0062_userprofile_legacy_search"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
