# Generated by Django 5.2.3

import logging

from django.db import migrations, models, transaction

from bookmarks.utils import normalize_url

logger = logging.getLogger(__name__)


def deduplicate_bookmarks(apps, schema_editor):
    """
    清理重复书签：
    1. 找出所有重复的 (owner, url_normalized) 组合
    2. 对于每组重复，合并数据（标签取并集、保留最新内容、最早日期）
    3. 删除多余的重复记录
    """
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    BookmarkToTagRelationShip = Bookmark.tags.through

    # 找出所有重复的 (owner, url_normalized) 组合
    # 排除 url_normalized 为空的记录（历史遗留数据）
    duplicates = (
        Bookmark.objects.exclude(url_normalized="")
        .values("owner", "url_normalized")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    total_groups = duplicates.count()
    if total_groups == 0:
        logger.info("No duplicate bookmarks found.")
        return

    logger.info(f"Found {total_groups} groups of duplicate bookmarks. Starting deduplication...")

    processed = 0
    for dup in duplicates:
        try:
            with transaction.atomic():
                # 获取该组所有书签，按 date_modified 降序（最新在前）
                bookmarks = list(
                    Bookmark.objects.filter(
                        owner=dup["owner"],
                        url_normalized=dup["url_normalized"],
                    ).order_by("-date_modified")
                )

                if len(bookmarks) <= 1:
                    continue

                # 保留最新的一条作为主记录
                primary = bookmarks[0]
                others = bookmarks[1:]

                # 合并标签：取并集
                all_tag_ids = set(
                    BookmarkToTagRelationShip.objects.filter(
                        bookmark=primary
                    ).values_list("tag_id", flat=True)
                )
                for other in others:
                    other_tag_ids = set(
                        BookmarkToTagRelationShip.objects.filter(
                            bookmark=other
                        ).values_list("tag_id", flat=True)
                    )
                    all_tag_ids.update(other_tag_ids)

                # 保留最早的 date_added
                all_date_added = [b.date_added for b in bookmarks if b.date_added]
                if all_date_added:
                    primary.date_added = min(all_date_added)

                primary.save()

                # 重新设置标签关联
                BookmarkToTagRelationShip.objects.filter(bookmark=primary).delete()
                BookmarkToTagRelationShip.objects.bulk_create(
                    [
                        BookmarkToTagRelationShip(bookmark=primary, tag_id=tag_id)
                        for tag_id in all_tag_ids
                    ]
                )

                # 删除其他重复记录
                for other in others:
                    other.delete()

                processed += 1
                if processed % 100 == 0:
                    logger.info(f"Processed {processed}/{total_groups} duplicate groups...")

        except Exception as e:
            logger.error(
                f"Error deduplicating bookmark (owner={dup['owner']}, url={dup['url_normalized']}): {e}"
            )
            continue

    logger.info(f"Deduplication complete. Processed {processed} duplicate groups.")


def reverse_deduplicate_bookmarks(apps, schema_editor):
    """反向操作：不做任何事情，因为无法恢复已删除的重复记录"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0063_migrate_api_tokens"),
    ]

    operations = [
        # 第1步：清理重复数据
        migrations.RunPython(
            deduplicate_bookmarks,
            reverse_deduplicate_bookmarks,
        ),
        # 第2步：添加唯一约束
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=["owner", "url_normalized"],
                name="unique_bookmark_url_per_user",
            ),
        ),
    ]
