# Generated by Django 5.2.3

import logging

from django.db import migrations, models, transaction

from bookmarks.utils import normalize_url

logger = logging.getLogger(__name__)


def _merge_bookmark_group(primary, others, BookmarkToTagRelationShip, BookmarkAsset):
    """合并一组重复书签，尽可能保留所有数据不丢失。"""

    # 1. 转移资产：将被合并书签的 BookmarkAsset 全部转给主记录
    other_ids = [o.id for o in others]
    BookmarkAsset.objects.filter(bookmark_id__in=other_ids).update(
        bookmark=primary
    )

    # 2. 转移 latest_snapshot：若主记录没有，从被合并书签中取最新的
    if not primary.latest_snapshot_id:
        for other in others:
            if other.latest_snapshot_id:
                primary.latest_snapshot = other.latest_snapshot
                break

    # 3. 合并文本字段：拼接所有书签的内容，用空行分隔
    all_bookmarks = [primary] + others
    for field in ["notes", "description"]:
        parts = []
        for b in all_bookmarks:
            val = getattr(b, field)
            if val:
                parts.append(val)
        if parts:
            setattr(primary, field, "\n\n".join(parts))

    # 3b. 其余字段：主记录为空时用被合并书签的内容补充
    for field in [
        "title",
        "web_archive_snapshot_url",
        "preview_image_file",
        "preview_image_remote_url",
        "favicon_file",
    ]:
        if not getattr(primary, field):
            for other in others:
                val = getattr(other, field)
                if val:
                    setattr(primary, field, val)
                    break

    # 4. 合并布尔字段
    primary.unread = primary.unread or any(o.unread for o in others)
    primary.shared = primary.shared or any(o.shared for o in others)
    primary.is_deleted = primary.is_deleted or any(o.is_deleted for o in others)
    primary.is_archived = all(o.is_archived for o in [primary] + others)

    # 5. 保留最早添加日期、最晚访问日期
    all_dates = [b.date_added for b in [primary] + others if b.date_added]
    if all_dates:
        primary.date_added = min(all_dates)
    all_accessed = [b.date_accessed for b in [primary] + others if b.date_accessed]
    if all_accessed:
        primary.date_accessed = max(all_accessed)

    # 6. 若主记录缺少规范化 URL，用一组 URL 填补
    if not primary.url_normalized:
        primary.url_normalized = normalize_url(primary.url)

    primary.save()

    # 7. 合并标签：取并集
    all_tag_ids = set(
        BookmarkToTagRelationShip.objects.filter(bookmark=primary).values_list(
            "tag_id", flat=True
        )
    )
    for other in others:
        other_tag_ids = set(
            BookmarkToTagRelationShip.objects.filter(bookmark=other).values_list(
                "tag_id", flat=True
            )
        )
        all_tag_ids.update(other_tag_ids)

    BookmarkToTagRelationShip.objects.filter(bookmark=primary).delete()
    BookmarkToTagRelationShip.objects.bulk_create(
        [
            BookmarkToTagRelationShip(bookmark=primary, tag_id=tag_id)
            for tag_id in all_tag_ids
        ]
    )

    # 8. 删除被合并书签（资产已转移，不会级联丢失）
    for other in others:
        other.delete()


def deduplicate_bookmarks(apps, schema_editor):
    """
    清理重复书签，分两轮：
    1. 处理 url_normalized 非空的重复组
    2. 处理 url_normalized 为空的重复组（按 owner + url 分组）
    最后确保空 url_normalized 的幸存记录被补填。
    """
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    BookmarkToTagRelationShip = Bookmark.tags.through
    BookmarkAsset = apps.get_model("bookmarks", "BookmarkAsset")

    # 第1轮：url_normalized 非空的重复
    duplicates = (
        Bookmark.objects.exclude(url_normalized="")
        .values("owner", "url_normalized")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    total_groups = duplicates.count()
    processed = 0
    if total_groups > 0:
        logger.info(
            f"Round 1: Found {total_groups} duplicate groups (non-empty url_normalized)."
        )
        for dup in duplicates:
            try:
                with transaction.atomic():
                    bookmarks = list(
                        Bookmark.objects.filter(
                            owner=dup["owner"],
                            url_normalized=dup["url_normalized"],
                        ).order_by("-date_modified")
                    )
                    if len(bookmarks) <= 1:
                        continue
                    _merge_bookmark_group(
                        bookmarks[0], bookmarks[1:], BookmarkToTagRelationShip, BookmarkAsset
                    )
                    processed += 1
                    if processed % 100 == 0:
                        logger.info(
                            f"Round 1: {processed}/{total_groups} groups processed..."
                        )
            except Exception as e:
                logger.error(
                    f"Error deduplicating (owner={dup['owner']}, "
                    f"url_normalized={dup['url_normalized']}): {e}"
                )
                continue
        logger.info(f"Round 1 complete. Processed {processed} groups.")

    # 第2轮：url_normalized 为空的重复，按 (owner, url) 分组
    empty_duplicates = (
        Bookmark.objects.filter(url_normalized="")
        .values("owner", "url")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    total_empty = empty_duplicates.count()
    empty_processed = 0
    if total_empty > 0:
        logger.info(
            f"Round 2: Found {total_empty} duplicate groups (empty url_normalized)."
        )
        for dup in empty_duplicates:
            try:
                with transaction.atomic():
                    bookmarks = list(
                        Bookmark.objects.filter(
                            owner=dup["owner"],
                            url=dup["url"],
                            url_normalized="",
                        ).order_by("-date_modified")
                    )
                    if len(bookmarks) <= 1:
                        continue
                    # 为主记录补填 url_normalized
                    primary = bookmarks[0]
                    primary.url_normalized = normalize_url(primary.url)
                    primary.save()
                    _merge_bookmark_group(
                        primary, bookmarks[1:], BookmarkToTagRelationShip, BookmarkAsset
                    )
                    empty_processed += 1
            except Exception as e:
                logger.error(
                    f"Error deduplicating empty-url (owner={dup['owner']}, "
                    f"url={dup['url']}): {e}"
                )
                continue
        logger.info(f"Round 2 complete. Processed {empty_processed} groups.")

    # 第3轮：补填剩余空 url_normalized 的孤立记录
    orphan_empty = Bookmark.objects.filter(url_normalized="")
    orphan_count = orphan_empty.count()
    if orphan_count > 0:
        logger.info(
            f"Round 3: Filling url_normalized for {orphan_count} orphan bookmarks."
        )
        for bookmark in orphan_empty.iterator(chunk_size=500):
            try:
                bookmark.url_normalized = normalize_url(bookmark.url)
                bookmark.save(update_fields=["url_normalized"])
            except Exception as e:
                logger.error(
                    f"Error normalizing URL for bookmark {bookmark.id}: {e}"
                )
                continue
        logger.info("Round 3 complete.")

    logger.info("Deduplication complete.")


def reverse_deduplicate_bookmarks(apps, schema_editor):
    """反向操作：不做任何事情，因为无法恢复已删除的重复记录"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0065_migrate_api_tokens"),
    ]

    operations = [
        # 第1步：清理重复数据
        migrations.RunPython(
            deduplicate_bookmarks,
            reverse_deduplicate_bookmarks,
        ),
        # 第2步：添加唯一约束
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                fields=["owner", "url_normalized"],
                name="unique_bookmark_url_per_user",
            ),
        ),
    ]
