# Generated by Django 5.2.3

import logging
import os
import sqlite3 as sqlite3_module

from django.db import migrations, models, transaction

# 用 CREATE UNIQUE INDEX（不重建表）代替 AddConstraint（会整表重建），
# 避免在 SQLite 隐性损坏时触发 database disk image is malformed。
SQL_CREATE_INDEX = (
    "CREATE UNIQUE INDEX IF NOT EXISTS unique_bookmark_url_per_user "
    "ON bookmarks_bookmark (owner_id, url_normalized)"
)

from bookmarks.utils import normalize_url

logger = logging.getLogger(__name__)


def _merge_bookmark_group(primary, others, BookmarkToTagRelationShip, BookmarkAsset):
    """合并一组重复书签，尽可能保留所有数据不丢失。"""

    # 1. 转移资产：将被合并书签的 BookmarkAsset 全部转给主记录
    other_ids = [o.id for o in others]
    BookmarkAsset.objects.filter(bookmark_id__in=other_ids).update(
        bookmark=primary
    )

    # 2. 转移 latest_snapshot：若主记录没有，从被合并书签中取最新的
    if not primary.latest_snapshot_id:
        for other in others:
            if other.latest_snapshot_id:
                primary.latest_snapshot = other.latest_snapshot
                break

    # 3. 合并文本字段：拼接所有书签的内容，用空行分隔
    all_bookmarks = [primary] + others
    for field in ["notes", "description"]:
        parts = []
        for b in all_bookmarks:
            val = getattr(b, field)
            if val:
                parts.append(val)
        if parts:
            setattr(primary, field, "\n\n".join(parts))

    # 3b. 其余字段：主记录为空时用被合并书签的内容补充
    for field in [
        "title",
        "web_archive_snapshot_url",
        "preview_image_file",
        "preview_image_remote_url",
        "favicon_file",
    ]:
        if not getattr(primary, field):
            for other in others:
                val = getattr(other, field)
                if val:
                    setattr(primary, field, val)
                    break

    # 4. 合并布尔字段
    primary.unread = primary.unread or any(o.unread for o in others)
    primary.shared = primary.shared or any(o.shared for o in others)
    primary.is_deleted = primary.is_deleted or any(o.is_deleted for o in others)
    primary.is_archived = all(o.is_archived for o in [primary] + others)

    # 5. 保留最早添加日期、最晚访问日期
    all_dates = [b.date_added for b in [primary] + others if b.date_added]
    if all_dates:
        primary.date_added = min(all_dates)
    all_accessed = [b.date_accessed for b in [primary] + others if b.date_accessed]
    if all_accessed:
        primary.date_accessed = max(all_accessed)

    # 6. 若主记录缺少规范化 URL，用一组 URL 填补
    if not primary.url_normalized:
        primary.url_normalized = normalize_url(primary.url)

    primary.save()

    # 7. 合并标签：取并集
    all_tag_ids = set(
        BookmarkToTagRelationShip.objects.filter(bookmark=primary).values_list(
            "tag_id", flat=True
        )
    )
    for other in others:
        other_tag_ids = set(
            BookmarkToTagRelationShip.objects.filter(bookmark=other).values_list(
                "tag_id", flat=True
            )
        )
        all_tag_ids.update(other_tag_ids)

    BookmarkToTagRelationShip.objects.filter(bookmark=primary).delete()
    BookmarkToTagRelationShip.objects.bulk_create(
        [
            BookmarkToTagRelationShip(bookmark=primary, tag_id=tag_id)
            for tag_id in all_tag_ids
        ]
    )

    # 8. 删除被合并书签（资产已转移，不会级联丢失）
    for other in others:
        other.delete()


def deduplicate_bookmarks(apps, schema_editor):
    """
    清理重复书签，分两步：
    1. 先把所有 url_normalized 为空的记录全部清洗填满。
    2. 全局按 (owner, url_normalized) 查找重复项并合并。
    """
    Bookmark = apps.get_model("bookmarks", "Bookmark")
    BookmarkToTagRelationShip = Bookmark.tags.through
    BookmarkAsset = apps.get_model("bookmarks", "BookmarkAsset")

    # 第 1 步：强制补全所有空缺的 url_normalized，暴露所有潜在的重复项
    empty_bookmarks = Bookmark.objects.filter(url_normalized="")
    empty_count = empty_bookmarks.count()
    if empty_count > 0:
        logger.info(f"Step 1: Normalizing {empty_count} bookmarks with empty url_normalized...")
        for bookmark in empty_bookmarks.iterator(chunk_size=500):
            try:
                bookmark.url_normalized = normalize_url(bookmark.url)
                bookmark.save(update_fields=["url_normalized"])
            except Exception as e:
                logger.error(f"Error normalizing URL for bookmark {bookmark.id}: {e}")

    # 第 2 步：此时库中不再有空的 url_normalized，进行全局去重
    duplicates = (
        Bookmark.objects.values("owner", "url_normalized")
        .annotate(count=models.Count("id"))
        .filter(count__gt=1)
    )

    total_groups = duplicates.count()
    processed = 0
    if total_groups > 0:
        logger.info(f"Step 2: Found {total_groups} duplicate groups globally.")
        for dup in duplicates:
            try:
                with transaction.atomic():
                    bookmarks = list(
                        Bookmark.objects.filter(
                            owner=dup["owner"],
                            url_normalized=dup["url_normalized"],
                        ).order_by("-date_modified")
                    )
                    if len(bookmarks) > 1:
                        _merge_bookmark_group(
                            bookmarks[0], bookmarks[1:], BookmarkToTagRelationShip, BookmarkAsset
                        )
                        processed += 1
                        if processed % 100 == 0:
                            logger.info(f"Step 2: {processed}/{total_groups} groups processed...")
            except Exception as e:
                logger.error(f"Error deduplicating (owner={dup['owner']}, url_normalized={dup['url_normalized']}): {e}")
                continue
        logger.info(f"Deduplication complete. Merged {processed} groups.")


def reverse_deduplicate_bookmarks(apps, schema_editor):
    """反向操作：不做任何事情，因为无法恢复已删除的重复记录"""
    pass


def _repair_database(db_path):
    """通过 dump + reload 修复 SQLite 隐性损坏，返回 True 表示成功。"""
    backup_path = db_path + ".repair_backup"
    new_path = db_path + ".repair_new"

    # 1. 先用当前连接 dump 出全部数据
    src_conn = sqlite3_module.connect(db_path)
    try:
        dump_sql = "".join(src_conn.iterdump())
    finally:
        src_conn.close()

    # 2. 写入新数据库文件
    dst_conn = sqlite3_module.connect(new_path)
    try:
        dst_conn.executescript(dump_sql)
        dst_conn.execute(SQL_CREATE_INDEX)
        dst_conn.commit()
    finally:
        dst_conn.close()

    # 3. 替换：原文件重命名为备份，新文件移到原位置
    if os.path.exists(backup_path):
        os.remove(backup_path)
    os.rename(db_path, backup_path)
    os.rename(new_path, db_path)

    logger.info(f"Database repaired. Original backed up to {backup_path}")
    return True


def create_index_safely(apps, schema_editor):
    try:
        schema_editor.execute(SQL_CREATE_INDEX)
    except Exception as e:
        if "database disk image is malformed" not in str(e):
            raise

        logger.warning("Database corruption detected. Attempting auto-repair...")
        db_path = schema_editor.connection.settings_dict["NAME"]
        try:
            # 关闭 Django 连接，释放文件锁
            schema_editor.connection.close()
            _repair_database(db_path)
            logger.info("Auto-repair successful. Index created on repaired database.")
        except Exception as repair_e:
            logger.error(
                "Auto-repair failed: %s\n"
                "Manual repair steps:\n"
                "  1. sqlite3 %s '.recover' | sqlite3 %s.recovered\n"
                "  2. mv %s.recovered %s && restart",
                repair_e, db_path, db_path, db_path, db_path,
            )
            raise


def drop_index_safely(apps, schema_editor):
    schema_editor.execute("DROP INDEX IF EXISTS unique_bookmark_url_per_user")


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0065_migrate_api_tokens"),
    ]

    operations = [
        # 第1步：清理重复数据
        migrations.RunPython(
            deduplicate_bookmarks,
            reverse_deduplicate_bookmarks,
        ),
        # 第2步：添加唯一约束
        # 用 CREATE INDEX 代替 AddConstraint，避免 SQLite 整表重建触发隐性损坏。
        # 已受损坏影响的用户会看到明确的修复指引而非无头错误堆栈。
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    create_index_safely,
                    drop_index_safely,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="bookmark",
                    constraint=models.UniqueConstraint(
                        fields=["owner", "url_normalized"],
                        name="unique_bookmark_url_per_user",
                    ),
                ),
            ],
        ),
    ]
