# Generated by Django 5.2.3 on 2026-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0066_deduplicate_bookmarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="domain_compact_mode",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="domain_view_mode",
            field=models.CharField(
                choices=[("full", "Full"), ("icon", "Icon")],
                default="icon",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sum_mode",
            field=models.CharField(
                choices=[("calendar", "Calendar"), ("heatmap", "Heatmap")],
                default="calendar",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sum_show_details",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sum_show_weekdays",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookmarkbundle",
            name="search_params",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Search parameters"
            ),
        ),
        migrations.AlterField(
            model_name="bookmarkbundle",
            name="show_count",
            field=models.BooleanField(default=True, verbose_name="Show bookmark count"),
        ),
        migrations.AlterField(
            model_name="globalsettings",
            name="landing_page",
            field=models.CharField(
                choices=[("login", "Login page"), ("shared_bookmarks", "Shared page")],
                default="login",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bookmark_date_display",
            field=models.CharField(
                choices=[
                    ("hidden", "Hidden"),
                    ("relative", "Relative"),
                    ("absolute", "Absolute"),
                ],
                default="relative",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bookmark_description_display",
            field=models.CharField(
                choices=[("inline", "Inline"), ("separate", "Separate")],
                default="inline",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bookmark_link_target",
            field=models.CharField(
                choices=[("_blank", "New page"), ("_self", "Same page")],
                default="_blank",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tag_grouping",
            field=models.CharField(
                choices=[("alphabetical", "Alphabetical"), ("disabled", "Disabled")],
                default="alphabetical",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="tag_search",
            field=models.CharField(
                choices=[("strict", "Strict"), ("lax", "Lax")],
                default="strict",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("auto", "Auto"), ("light", "Light"), ("dark", "Dark")],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="web_archive_integration",
            field=models.CharField(
                choices=[("disabled", "Disabled"), ("enabled", "Enabled")],
                default="disabled",
                max_length=10,
            ),
        ),
    ]
