# Generated by Django 6.0.4 on 2026-05-07 13:02

from django.db import migrations, models

# 约束已在 0066 通过 AddConstraint 添加，0067 不再移除。
# 对于已从 v1.0.4（旧编号 0065 包含 RemoveConstraint）升级的用户，
# DatabaseError 会被捕获跳过，因为 SQLite 在约束已存在时会报错。
SQL_ADD_CONSTRAINT = (
    "CREATE UNIQUE INDEX IF NOT EXISTS unique_bookmark_url_per_user "
    "ON bookmarks_bookmark (owner_id, url_normalized)"
)

SQL_DROP_CONSTRAINT = "DROP INDEX IF EXISTS unique_bookmark_url_per_user"


def add_constraint_if_missing(apps, schema_editor):
    """补添加唯一约束，已存在则跳过。"""
    try:
        schema_editor.execute(SQL_ADD_CONSTRAINT)
    except Exception:
        pass


def drop_constraint(apps, schema_editor):
    schema_editor.execute(SQL_DROP_CONSTRAINT)


class Migration(migrations.Migration):

    dependencies = [
        ("bookmarks", "0067_userprofile_summary_domain_prefs"),
    ]

    operations = [
        # 补添加唯一约束（对于成功升级到旧 v1.0.4 的用户，约束被旧 0065 删除了；
        # 对于全新安装，约束在 0066 已添加，IF NOT EXISTS 会跳过）。
        migrations.RunPython(add_constraint_if_missing, drop_constraint),
        migrations.AlterField(
            model_name="userprofile",
            name="default_mark_unread",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="enable_favicons",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sticky_header_controls",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sticky_pagination",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sticky_side_panel",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sum_mode",
            field=models.CharField(
                choices=[("calendar", "Calendar"), ("heatmap", "Heatmap")],
                default="heatmap",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="sum_show_details",
            field=models.BooleanField(default=True),
        ),
    ]
